/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Devoleum, DevoleumInterface } from "../../src/Devoleum";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "_hashOfJson",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_createdAt",
        type: "uint256",
      },
    ],
    name: "StepProofCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "allowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hashOfJson",
        type: "bytes32",
      },
    ],
    name: "createStepProof",
    outputs: [
      {
        internalType: "uint256",
        name: "_createdAt",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "hashToDate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "selfDisableAllowed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "toggleAllowed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610393806100326000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80635a4084cd146100675780638da5cb5b1461009a57806393db67a5146100c5578063978ee3a6146100da578063bedeaeb7146100ed578063d63a8e11146100f5575b600080fd5b610087610075366004610314565b60016020526000908152604090205481565b6040519081526020015b60405180910390f35b6000546100ad906001600160a01b031681565b6040516001600160a01b039091168152602001610091565b6100d86100d336600461032d565b610128565b005b6100876100e8366004610314565b61019d565b6100d86102ad565b61011861010336600461032d565b60026020526000908152604090205460ff1681565b6040519015158152602001610091565b6000546001600160a01b031633146101745760405162461bcd60e51b815260206004820152600a60248201526927b7363c9037bbb732b960b11b60448201526064015b60405180910390fd5b6001600160a01b03166000908152600260205260409020805460ff19811660ff90911615179055565b3360009081526002602052604081205460ff16806101c557506000546001600160a01b031633145b6102005760405162461bcd60e51b815260206004820152600c60248201526b13db9b1e48185b1b1bddd95960a21b604482015260640161016b565b60008281526001602052604090205482901561024a5760405162461bcd60e51b81526020600482015260096024820152686475706c696361746560b81b604482015260640161016b565b60008381526001602090815260409182902042908190558251868152918201819052917f3c2d8735e493f7014ca90c4af14df8dd5e895d6aebf1c644a6b141ab9042b453910160405180910390a150505060009081526001602052604090205490565b3360009081526002602052604090205460ff166102fb5760405162461bcd60e51b815260206004820152600c60248201526b13db9b1e48185b1b1bddd95960a21b604482015260640161016b565b336000908152600260205260409020805460ff19169055565b60006020828403121561032657600080fd5b5035919050565b60006020828403121561033f57600080fd5b81356001600160a01b038116811461035657600080fd5b939250505056fea26469706673582212209b3dd41bd2416c7cca50542cfca6ae1af7d11bf7ff265bb2dc7a5b993ed1f27164736f6c634300080f0033";

type DevoleumConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DevoleumConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Devoleum__factory extends ContractFactory {
  constructor(...args: DevoleumConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Devoleum> {
    return super.deploy(overrides || {}) as Promise<Devoleum>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Devoleum {
    return super.attach(address) as Devoleum;
  }
  override connect(signer: Signer): Devoleum__factory {
    return super.connect(signer) as Devoleum__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DevoleumInterface {
    return new utils.Interface(_abi) as DevoleumInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Devoleum {
    return new Contract(address, _abi, signerOrProvider) as Devoleum;
  }
}
