[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  environment = { NODE_VERSION = "16" }

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"