name: Hardhat Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Show NodeJS version
        run: npm --version

      - name: Install hardhat
        run: npm install hardhat

      - name: Install Dependencies
        run: npm install

      - name: Run hardhat Test
        run: npx hardhat test

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Show Python version
        run: python --version

      - name: Clone SmartBugs Repo
        run: git clone https://github.com/smartbugs/smartbugs.git
      - name: Remove SmartBugs Results and Install SmartBugs Dependencies
        run: cd smartbugs;rm -r results;pip install -r requirements.txt
      - name: Run SmartBugs Analysis
        run: |
          solidityFiles=($(ls -I Migrations.sol src))
          DIR=$(pwd);cd smartbugs
          for sol in "${solidityFiles[@]}"
          do
            echo "Analysing $sol..."
            python smartBugs.py --tool oyente slither smartcheck solhint --file $DIR/contracts/$sol
          done

      - name: Move SmartBugs Results to Parent Directory
        run: |
          [[ -d results ]] && rm -r results
          cd smartbugs
          mv results ../
      - name: Commit SmartBugs Results
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: action@github.com
          message: "chore: added smartbugs results"
          add: "results"
